Repository linkernetworks/vortex, pull requests merged in 2018-07, with the labels that each got.

#65 Create a deployment for storage.
  src/entity/storage.go
  src/kubernetes/deployment.go
  src/kubernetes/deployment_test.go
  src/server/handler_storage.go
  src/server/handler_storage_test.go
  src/storageprovider/fake.go
  src/storageprovider/fake_test.go
  src/storageprovider/nfs.go
  src/storageprovider/nfs_test.go
  src/storageprovider/storage.go
  src/storageprovider/storage_test.go
Labels: Feature

#68 Use the namespace in the kubectl object
  src/kubernetes/pods.go
  src/kubernetes/pods_test.go
  src/kubernetes/pvc.go
  src/kubernetes/pvc_test.go
Labels: bug

#66 Create/Delete the storageClass when we create/delete the storage
  deploy/kubernetes/auth/clusterrole.yaml
  deploy/kubernetes/auth/clusterrolebinding.yaml
  deploy/kubernetes/auth/nfs-provisioner.yaml
  src/entity/storage.go
  src/kubernetes/storageclass.go
  src/kubernetes/storageclass_test.go
  src/server/handler_storage_test.go
  src/storageprovider/nfs.go
  src/storageprovider/nfs_test.go
Labels: Feature

#71 Support the create/delete for volume(pvc) via restful API
  src/entity/volume.go
  src/server/handler_volume.go
  src/server/handler_volume_test.go
  src/storageprovider/nfs_test.go
  src/volume/volume.go
  src/volume/volume_test.go
Labels: Feature

#70 DEV VX69: List handler for all resource, and get handler for pod and service.
  deploy/kubernetes/apps/monitoring/cadvisor/cadvisor-svc.yaml
  deploy/kubernetes/apps/monitoring/cadvisor/cadvisor.yaml
  src/config/config.go
  src/entity/metrics_container.go
  src/entity/metrics_controller.go
  src/entity/metrics_node.go
  src/entity/metrics_pod.go
  src/entity/metrics_service.go
  src/prometheuscontroller/expression.go
  src/prometheuscontroller/query.go
  src/prometheusprovider/promehteus.go
  src/server/handler_metrics_container.go
  src/server/handler_metrics_controller.go
  src/server/handler_metrics_node.go
  src/server/handler_metrics_pod.go
  src/server/handler_metrics_service.go
  src/server/handler_prometheus.go
  src/server/handler_prometheus_test.go
  src/server/route.go
  src/serviceprovider/serviceprovider.go
Labels: Feature

#74 Check the volume before deleting the storage
  src/storageprovider/nfs.go
  src/storageprovider/nfs_test.go
Labels: enhancement

#95 Support kubernetres cluster in the TravisCI
  .travis.yml
  deploy/kubernetes/apps/monitoring/cadvisor/cadvisor.yaml
Labels: enhancement

#186 [Task] Support hostnetwork option when creating Pod
  API.md
  src/entity/pod.go
  src/pod/pod.go
  src/server/handler_pod_test.go
  tests/pod.json
Labels: Feature
